ALTER TABLE AdminSettings ADD COLUMN Api2Url STRING;
ALTER TABLE AdminSettings ADD COLUMN Api2Version STRING;
ALTER TABLE AdminSettings ADD COLUMN Api2Key STRING;
ALTER TABLE AdminSettings ADD COLUMN ShowRosters BOOLEAN;
ALTER TABLE AdminSettings ADD COLUMN SecondEndpoint BOOLEAN;