ALTER TABLE Questions ADD COLUMN NumberInGrid INTEGER;
ALTER TABLE Grids ADD COLUMN Deleted BOOLEAN;
ALTER TABLE GridLabels ADD COLUMN Deleted BOOLEAN;
ALTER TABLE Grids ADD COLUMN Instructions STRING;
ALTER TABLE GridLabels ADD COLUMN Position INTEGER;