ALTER TABLE Questions ADD COLUMN LoopQuestionCount INTEGER;
ALTER TABLE Questions ADD COLUMN LoopSource STRING;
ALTER TABLE Questions ADD COLUMN LoopNumber INTEGER;
ALTER TABLE Instruments ADD COLUMN LoopsSet BOOLEAN;